{
 "title": "Nftables",
 "description": "OpenWrt firewall",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Traffic per rule",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(chain) (nftables_rule_bytes) > 0",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Packet per rule",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(chain) (nftables_rule_packets) > 0",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "All rules",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "nftables_rule_bytes >= 1", "legendFormat": "{{exported_name}}" }
   ]
  }
 ]
}